### ISSUE TITLE
Absolute copy number caller type CNVkit 

### ISSUE THREAD

**Issue by TnakaNY** [ShixiangWang/sigflow#24]
Recommended absolute copy number caller is FACETS or Sequenza.
Has anybody compared CNVkit output wtih FACETS/Sequenza?

**Comment by ShixiangWang** [comment]
@TnakaNY The core data for copy number analysis is that the copy number value must be integer, not copy number ratio. I used some softwares one or two years ago to do this and found that FACETS or Sequenza is suitable. Sigminer/sigflow does not care the input data come from.

Recently, I also found ASCAT is pretty useful and can also report integer copy number.

CNVkit seems a very powerful CNV caller, but I don't know if it supports outputting integer copy number (may be https://cnvkit.readthedocs.io/en/stable/baf.html but I cannot see the example output).

By googling, I cannot find a review paper to compare methods above, you can check this by your own. I found that the 4 methods metioned above all got >200 citations and should be good for common analysis. Just pick up a tool you are familar with.

Shixiang

---

Link to https://github.com/ShixiangWang/sigminer/issues/278 for reminding that adding this info to doc site.

**Comment by TnakaNY** [comment]
Hi,
Thank you for prompt reply. 

All my data is WGS. CNVkit has "call" function that convert its CN log ratio output to absolute int copy number (.cns to .call.cns file). Also, CNVkit converts its output to SEG files for input to GISTIC2.0. At this time, I guess, I do not need to use GISTIC2.0 again due to already having absolute copy number.

Thanks.
