### ISSUE TITLE
/usr/local/bin suggestion for installing

### ISSUE THREAD

**Issue by ahorn720** [ShixiangWang/sigflow#29]
Hi There!

I'm on a macOS device running Catalina 10.15.7 and I was having trouble creating the symlink you recommended in the instructions because modifying `/usr/bin` is disallowed by System Integrity Protection.

I would suggest changing it from `/usr/bin` to `/usr/local/bin` so that this suggestion works for macOS as well (it worked for me).

Thanks!

**Comment by ShixiangWang** [comment]
Thanks for your report and suggestion.
