### ISSUE TITLE
奇怪的BUG：报错信息solving row 120798: 'allow.nonnarrowing' is FALSE and the supplied end (16581) is > refwidth

### ISSUE THREAD

**Issue by b-niu** [ShixiangWang/sigflow#32]
Dear @ShixiangWang ,

在运行sigflow时，遇到了一个报错信息：
![image](https://user-images.githubusercontent.com/32410912/153702840-dec34940-f192-4aac-94dc-b0430c8bbd09.png)

查询得知，一般该报错来自于使用了错误的参考基因组，导致坐标出界。例如：
https://github.com/PoisonAlien/maftools/issues/85

但是我仔细检查了使用的基因组，确认bwa比对和sigflow使用的都是hg19，且报错的这一行row 120798的坐标信息确实位于基因组内。

根据 https://www.genome.ucsc.edu/goldenpath/help/hg19.chrom.sizes：
chr15 size = 102531392
row 120798是
![image](https://user-images.githubusercontent.com/32410912/153702969-4616612b-e067-47ba-9400-a6b0a8f28d93.png)

![image](https://user-images.githubusercontent.com/32410912/153702961-3d6dd15e-7262-4641-a995-932f39589c76.png)

请问您有什么线索可以让我找出错误所在吗？
谢谢

**Comment by b-niu** [comment]
更新一些信息：

目前已经定位，报错位于`sig_tally()`函数。将chrM染色体的变异移除后，程序可以成功运行。
仔细检查了下，未发现chrM上有变异的位点大于chrM的染色体size。希望这些信息能有帮助。

**Comment by ShixiangWang** [comment]
@b-niu 谢谢report。这个可能是基因组版本不完全兼容造成的。
