### ISSUE TITLE
what is the input format of rearrangement signature ?

### ISSUE THREAD

**Issue by Aimee2018** [ShixiangWang/sigflow#33]
Hello, I want to find the signature of SV data. what is the input format of rearrangement signature? Thank you!

**Comment by ShixiangWang** [comment]
@Aimee2018 Hi, the sigflow does not support rearrangement signature, please refer to sigminer directly. The data import function is located at https://shixiangwang.github.io/sigminer/reference/read_sv_as_rs.html, you can check the example data for input format.

**Comment by Aimee2018** [comment]
Thanks a lot for your reply! I get the right input format. However, I still cannot get the best practice from data to visualize for the rearrangement signatures.&nbsp;


As the guideline, I got the sig_tally. But, There is not any information about the signature information.





Could you give me some suggestions for analysis the SV rearrangement signature and the final signature visualization?
how to get the result as follow:



Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShixiangWang/sigflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月12日(星期三) 上午9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ShixiangWang/sigflow] what is the input format of rearrangement signature ? (Issue #33)





 
@Aimee2018 Hi, the sigflow does not support rearrangement signature, please refer to sigminer directly. The data import function is located at https://shixiangwang.github.io/sigminer/reference/read_sv_as_rs.html, you can check the example data for input format.

**Comment by ShixiangWang** [comment]
@Aimee2018 I cannot see the pictures from you, here shows a quick example demonstrating the basic usage:

```r
library(sigminer)

sv <- readRDS(system.file("extdata", "toy_sv.rds", package = "sigminer", mustWork = TRUE))
rs <- read_sv_as_rs(sv)
tally_rs <- sig_tally(rs)

rs_sig <- sig_auto_extract(tally_rs$nmf_matrix)

show_sig_profile(rs_sig, mode = "RS", style = "cosmic")
show_sig_exposure(rs_sig)

# Get signature matrix
sig_signature(rs_sig)
# Get activity/contribution
sig_exposure(rs_sig)
sig_exposure(rs_sig, type = "relative")
```

**Comment by Aimee2018** [comment]
Got it ! Thank you so much！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShixiangWang/sigflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月12日(星期三) 下午4:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ShixiangWang/sigflow] what is the input format of rearrangement signature ? (Issue #33)





 
@Aimee2018 I cannot see the pictures from you, here shows a quick example demonstrating the basic usage:
 library(sigminer) sv <- readRDS(system.file("extdata", "toy_sv.rds", package = "sigminer", mustWork = TRUE)) rs <- read_sv_as_rs(sv) tally_rs <- sig_tally(rs) rs_sig <- sig_auto_extract(tally_rs$nmf_matrix) show_sig_profile(rs_sig, mode = "RS", style = "cosmic") show_sig_exposure(rs_sig) # Get signature matrix sig_signature(rs_sig) # Get activity/contribution sig_exposure(rs_sig) sig_exposure(rs_sig, type = "relative")

**Comment by ShixiangWang** [comment]
@Aimee2018 I am closing this issue now. If you got futher question, please file an issue on sigminer repo.
