### ISSUE TITLE
Cannot set hg38 for genome in container model

### ISSUE THREAD

**Issue by jpcartailler** [ShixiangWang/sigflow#34]
Greetings,

I'm trying to set the genome via `-g hg38` on version 2.2, from the Docker container. However, I get:

```
Try parsing VCF files...
Reading file(s): /data/cds_group/Processed-Data/2023-275-Jan_T-WGS-Cutaneous-Squamous-Cell-Carcinoma/results/130-mut-sig/GSQ062-DM/input/GSQ062-DM.vcf
Annotating Variant Type...
Downloading https://zenodo.org/record/4771552/files/human_hg38_gene_info.rds to /usr/local/lib/R/site-library/sigminer/extdata/human_hg38_gene_info.rds
Error in gzfile(file, "rb") : cannot open the connection
Calls: <Anonymous> -> readRDS -> gzfile
In addition: Warning messages:
1: In download.file(url = x_url, destfile = x_dest) :
  URL https://zenodo.org/record/4771552/files/human_hg38_gene_info.rds: cannot open destfile '/usr/local/lib/R/site-library/sigminer/extdata/human_hg38_gene_info.rds', reason 'Read-only file system'
2: In download.file(url = x_url, destfile = x_dest) :
  download had nonzero exit status
3: In gzfile(file, "rb") :
  cannot open compressed file '/usr/local/lib/R/site-library/sigminer/extdata/human_hg38_gene_info.rds', probable reason 'No such file or directory'
Execution halted
```

Please note that this is actually run from a Singularity image (from your Docker image, TY). The image is not writeable, which explains the `cannot open connection` error. We use Singularity on our HPC since Docker isn't allowed. 

Would it be possible for the `human_hg38_gene_info.rds` to be downloaded to the host machine, vs the guest (container)? That would bypass such permission problems. 

I couldn't find the code reference to `https://zenodo.org/record/4771552/files/human_hg38_gene_info.rds ` in sigflow or sigminer.. happy to help recode this, but unclear where the code actually is. Thanks!

**Comment by ShixiangWang** [comment]
@jpcartailler Thanks for your report. It seems a permission issue in the docker container, I will take a check.

**Comment by ShixiangWang** [comment]
@jpcartailler Could you run with the `master` tag of docker image again? I have added the data into the latest build container.

https://github.com/ShixiangWang/sigflow/actions/runs/8504003290/job/23290297823#step:8:33294

**Comment by jpcartailler** [comment]
@ShixiangWang Thank you for updating this. I tested the `master` tag of the docker image - hg38 option works now.

**Comment by ShixiangWang** [comment]
Great to hear that.
