### ISSUE TITLE
Running on .maf file - An error is detected in extract process. Quit the program!

### ISSUE THREAD

**Issue by szakallasn3** [ShixiangWang/sigflow#35]
Dear All, 
I am trying to perform signature analysis with sigflow with the following command on a .maf file:
_perl sigflow.R extract -i /maf -o /output_dir -r 10 -T 4 --max 10 -g hg38 --verbose --sigprofiler_

However, I usually end up with an error message saying: 
_An error is detected in extract process. Quit the program!_

I checked the output directory, and only the SBS_tally.csv is generated nothing else. 
Do you have any suggestions regarding this issue?

The verbose message is the following:

Name   :       sigflow
Author :       Shixiang Wang
Version:       2.2
License:       AFL 3.0
Link   :       https://github.com/ShixiangWang/sigflow
Doc    :       https://github.com/ShixiangWang/sigflow

Parsing parameters

extract         : TRUE
fit             : FALSE
bt              : FALSE
show            : FALSE
help            : FALSE
version         : FALSE
input           : /data/storage/hdd/shared/Szekvenálások/Nanopore_study/CRC/crc_mafs/5846_crc_bio.maf
output          : /data/storage/hdd/containervolumes/jupyter/home/niki/sigflow/test_results/5846crc_vcf
index           : ALL
mode            : SBS
manual          : FALSE
number          : 0
max             : 10
genome          : hg38
nrun            : 10
cores           : 4
refit           : FALSE
hyper           : FALSE
sigprofiler     : TRUE
isearch         : NULL
verbose         : TRUE

User command calling: /usr/lib64/R/bin/exec/R --no-echo --no-restore --file=/data/storage/hdd/containervolumes/jupyter/home/niki/sigflow/sigflow.R --args extract -i /data/storage/hdd/shared/Szekvenálások/Nanopore_study/CRC/crc_mafs/5846_crc_bio.maf -o /data/storage/hdd/containervolumes/jupyter/home/niki/sigflow/test_results/5846crc_vcf -r 10 -T 4 --max 10 -g hg38 --verbose --sigprofiler

Library:        /data/storage/hdd/containervolumes/jupyter/home/niki/R/x86_64-redhat-linux-gnu-library/4.4      /usr/lib64/R/library  /usr/share/R/library
R version 4.4.1 (2024-06-14)
Platform: x86_64-redhat-linux-gnu
Running under: Fedora Linux 40 (Container Image)

Matrix products: default
BLAS/LAPACK: FlexiBLAS OPENBLAS-OPENMP;  LAPACK version 3.11.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pheatmap_1.0.12     ggplot2_3.5.1       sigminer_2.3.2     
[4] Biobase_2.64.0      BiocGenerics_0.50.0 docopt_0.7.1       

loaded via a namespace (and not attached):
 [1] utf8_1.2.4          future_1.34.0       generics_0.1.3     
 [4] stringi_1.8.4       listenv_0.9.1       digest_0.6.37      
 [7] magrittr_2.0.3      grid_4.4.1          RColorBrewer_1.1-3 
[10] iterators_1.0.14    foreach_1.5.2       doParallel_1.0.17  
[13] plyr_1.8.9          BiocManager_1.30.25 purrr_1.0.2        
[16] fansi_1.0.6         scales_1.3.0        codetools_0.2-20   
[19] cli_3.6.3           registry_0.5-1      rlang_1.1.4        
[22] parallelly_1.38.0   munsell_0.5.1       withr_3.0.1        
[25] tools_4.4.1         parallel_4.4.1      reshape2_1.4.4     
[28] dplyr_1.1.4         colorspace_2.1-1    rngtools_1.5.2     
[31] NMF_0.28            globals_0.16.3      vctrs_0.6.5        
[34] R6_2.5.1            lifecycle_1.0.4     stringr_1.5.1      
[37] furrr_0.3.1         cluster_2.1.6       pkgconfig_2.0.3    
[40] pillar_1.9.0        gtable_0.3.5        glue_1.8.0         
[43] data.table_1.16.0   Rcpp_1.0.13         tibble_3.2.1       
[46] tidyselect_1.2.1    rstudioapi_0.16.0   compiler_4.4.1     
[49] gridBase_0.4-7     
Reading file...

Result directory /data/storage/hdd/containervolumes/jupyter/home/niki/sigflow/test_results/5846crc_vcf existed.

Running signature extraction pipeline...

ℹ [2024-10-09 13:24:31.141316]: Pipeline for extraction started.
ℹ [2024-10-09 13:24:37.846259]: Started.
ℹ [2024-10-09 13:24:37.982018]: We would assume you marked all variants' position in + strand.
✔ [2024-10-09 13:24:37.986513]: Reference genome loaded.
✔ [2024-10-09 13:24:38.101118]: Variants from MAF object queried.
✔ [2024-10-09 13:24:38.119594]: Chromosome names checked.
✔ [2024-10-09 13:24:38.18857]: Sex chromosomes properly handled.
✔ [2024-10-09 13:24:38.19327]: Only variants located in standard chromosomes (1:22, X, Y, M/MT) are kept.
✔ [2024-10-09 13:24:38.267907]: Variant start and end position checked.
✔ [2024-10-09 13:24:38.278823]: Variant data for matrix generation preprocessed.
ℹ [2024-10-09 13:24:38.281377]: All types of matrices generation - start.
ℹ [2024-10-09 13:24:38.284539]: SBS matrix generation - start.
ℹ [2024-10-09 13:24:38.28942]: Extracting 5' and 3' adjacent bases.
ℹ [2024-10-09 13:24:38.902357]: Extracting +/- 20bp around mutated bases for background C>T estimation.
ℹ [2024-10-09 13:24:40.221052]: Estimating APOBEC enrichment scores.
ℹ [2024-10-09 13:24:40.223992]: Performing one-way Fisher's test for APOBEC enrichment.
✔ [2024-10-09 13:24:40.251844]: APOBEC related mutations are enriched in 0% of samples (APOBEC enrichment score > 2; 0 of 1 samples)
ℹ [2024-10-09 13:24:40.2558]: Creating SBS sample-by-component matrices.
✔ [2024-10-09 13:24:40.281899]: SBS-6 matrix created.
✔ [2024-10-09 13:24:40.314201]: SBS-96 matrix created.
✔ [2024-10-09 13:24:40.352361]: SBS-1536 matrix created.
ℹ [2024-10-09 13:24:40.354634]: Return SBS-96 as major matrix.
ℹ [2024-10-09 13:24:40.359429]: DBS matrix generation - start.
ℹ [2024-10-09 13:24:40.364713]: Searching DBS records...
✔ [2024-10-09 13:24:41.489834]: Done.
✔ [2024-10-09 13:24:42.166677]: Reference sequences queried from genome.
✔ [2024-10-09 13:24:42.196291]: DBS-78 matrix created.
✔ [2024-10-09 13:24:42.221087]: DBS-1248 matrix created.
ℹ [2024-10-09 13:24:42.224009]: Return SBS-78 as major matrix.
ℹ [2024-10-09 13:24:42.229357]: INDEL matrix generation - start.
✔ [2024-10-09 13:24:43.455276]: Reference sequences queried from genome.
✔ [2024-10-09 13:24:43.458995]: INDEL length extracted.
✔ [2024-10-09 13:24:43.560483]: Adjacent copies counted.
✔ [2024-10-09 13:24:43.619033]: Microhomology size calculated.
✔ [2024-10-09 13:24:43.711955]: INDEL records classified into different components (types).
✔ [2024-10-09 13:24:43.724223]: ID-28 matrix created.
✔ [2024-10-09 13:24:43.738491]: ID-83 matrix created.
ℹ [2024-10-09 13:24:43.741084]: Return ID-83 as major matrix.
ℹ [2024-10-09 13:24:43.743828]: All types of matrices generation (APOBEC scores included) - end.
✔ [2024-10-09 13:24:43.74627]: Done.
ℹ [2024-10-09 13:24:43.749014]: 5.902 secs elapsed.
Outputing tally results for SBS
✖ [2024-10-09 13:24:43.759212]: You may choose wrong 'mode' option, this is designed for 'SBS'.
ℹ [2024-10-09 13:24:43.76215]: 12.621 secs elapsed.
An error is detected in extract process. Quit the program!

**Comment by ShixiangWang** [comment]
Hi @szakallasn3, have you tested with builtin example dataset?

https://github.com/ShixiangWang/sigflow/blob/master/test/test.sh

**Comment by szakallasn3** [comment]
Yes, I tested it on the tcga_laml.maf.gz dataset, and worked fine. However, when I tried to use a .maf among our files, I got the above mentioned error message.

**Comment by ShixiangWang** [comment]
If the example dataset is good, some unexpected data were generated during the output tally process (<https://github.com/ShixiangWang/sigminer/blob/9455b46c84ac47bbb35d77aed70e74875718c18f/R/output.R#L10>). May I have your (part of) maf data (can reproduce the error on your side) to debug the issue? (if yes, please send it to wangshx@csu.edu.cn)

**Comment by szakallasn3** [comment]
@ShixiangWang, I sent the .maf file to you via email.

**Comment by ShixiangWang** [comment]
@szakallasn3 Thanks for your email, I can reproduce the error. I will see how to fix it.

```r
~/Documents/GitHub/sigflow/sigflow.R extract -i 5846_crc_bio.maf -o test_out -r 10 -T 4 --max 10 -g hg38 --verbose

=================================================================

       .__        _____.__
  _____|__| _____/ ____\  |   ______  _  __
 /  ___/  |/ ___\   __\|  |  /  _ \ \/ \/ /
 \___ \|  / /_/  >  |  |  |_(  <_> )     /
/____  >__\___  /|__|  |____/\____/ \/\_/
     \/  /_____/

Name   :       sigflow
Author :       Shixiang Wang
Version:       2.2
License:       AFL 3.0
Link   :       https://github.com/ShixiangWang/sigflow
Doc    :       https://github.com/ShixiangWang/sigflow
============================== START

Parsing parameters...
------
extract		: TRUE
fit		: FALSE
bt		: FALSE
show		: FALSE
help		: FALSE
version		: FALSE
input		: 5846_crc_bio.maf
output		: test_out
index		: ALL
mode		: SBS
manual		: FALSE
number		: 0
max		: 10
genome		: hg38
nrun		: 10
cores		: 4
refit		: FALSE
hyper		: FALSE
sigprofiler	: FALSE
isearch		: NULL
verbose		: TRUE
------

User command calling: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/bin/exec/R --no-echo --no-restore --file=/Users/wsx/Documents/GitHub/sigflow/sigflow.R --args extract -i 5846_crc_bio.maf -o test_out -r 10 -T 4 --max 10 -g hg38 --verbose
------


Library:	/Users/wsx/Library/R/arm64/4.4/library	/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
R version 4.4.1 (2024-06-14)
Platform: aarch64-apple-darwin20
Running under: macOS 15.0.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] C/UTF-8/C/C/C/C

time zone: Asia/Shanghai
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] pheatmap_1.0.12     ggplot2_3.5.1       sigminer_2.3.1
[4] Biobase_2.64.0      BiocGenerics_0.50.0 docopt_0.7.1

loaded via a namespace (and not attached):
 [1] utf8_1.2.4          future_1.34.0       generics_0.1.3
 [4] stringi_1.8.4       listenv_0.9.1       digest_0.6.37
 [7] magrittr_2.0.3      grid_4.4.1          RColorBrewer_1.1-3
[10] iterators_1.0.14    foreach_1.5.2       doParallel_1.0.17
[13] plyr_1.8.9          BiocManager_1.30.25 purrr_1.0.2
[16] fansi_1.0.6         scales_1.3.0        codetools_0.2-20
[19] cli_3.6.3           registry_0.5-1      rlang_1.1.4
[22] parallelly_1.38.0   munsell_0.5.1       withr_3.0.1
[25] tools_4.4.1         parallel_4.4.1      reshape2_1.4.4
[28] dplyr_1.1.4         colorspace_2.1-1    rngtools_1.5.2
[31] NMF_0.28            globals_0.16.3      vctrs_0.6.5
[34] R6_2.5.1            lifecycle_1.0.4     stringr_1.5.1
[37] furrr_0.3.1         cluster_2.1.6       pkgconfig_2.0.3
[40] pillar_1.9.0        gtable_0.3.5        glue_1.7.0
[43] data.table_1.16.0   Rcpp_1.0.13         tibble_3.2.1
[46] tidyselect_1.2.1    compiler_4.4.1      gridBase_0.4-7
Reading file...
------
Result directory test_out existed.
------

Running signature extraction pipeline...
------
ℹ [2024-10-12 08:53:17.559612]: Pipeline for extraction started.
ℹ [2024-10-12 08:53:20.553417]: Started.
ℹ [2024-10-12 08:53:20.58475]: We would assume you marked all variants' position in + strand.
✔ [2024-10-12 08:53:20.586098]: Reference genome loaded.
✔ [2024-10-12 08:53:20.639242]: Variants from MAF object queried.
✔ [2024-10-12 08:53:20.652543]: Chromosome names checked.
✔ [2024-10-12 08:53:20.697761]: Sex chromosomes properly handled.
✔ [2024-10-12 08:53:20.699766]: Only variants located in standard chromosomes (1:22, X, Y, M/MT) are kept.
✔ [2024-10-12 08:53:20.729188]: Variant start and end position checked.
✔ [2024-10-12 08:53:20.73186]: Variant data for matrix generation preprocessed.
ℹ [2024-10-12 08:53:20.732506]: All types of matrices generation - start.
ℹ [2024-10-12 08:53:20.733577]: SBS matrix generation - start.
ℹ [2024-10-12 08:53:20.735533]: Extracting 5' and 3' adjacent bases.
ℹ [2024-10-12 08:53:21.081845]: Extracting +/- 20bp around mutated bases for background C>T estimation.
ℹ [2024-10-12 08:53:21.697339]: Estimating APOBEC enrichment scores.
ℹ [2024-10-12 08:53:21.698251]: Performing one-way Fisher's test for APOBEC enrichment.
✔ [2024-10-12 08:53:21.711554]: APOBEC related mutations are enriched in 0% of samples (APOBEC enrichment score > 2; 0 of 1 samples)
ℹ [2024-10-12 08:53:21.712981]: Creating SBS sample-by-component matrices.
✔ [2024-10-12 08:53:21.71511]: SBS-6 matrix created.
✔ [2024-10-12 08:53:21.717234]: SBS-96 matrix created.
✔ [2024-10-12 08:53:21.722413]: SBS-1536 matrix created.
ℹ [2024-10-12 08:53:21.723077]: Return SBS-96 as major matrix.
ℹ [2024-10-12 08:53:21.724368]: DBS matrix generation - start.
ℹ [2024-10-12 08:53:21.725959]: Searching DBS records...
✔ [2024-10-12 08:53:22.12026]: Done.
✔ [2024-10-12 08:53:22.459548]: Reference sequences queried from genome.
✔ [2024-10-12 08:53:22.464511]: DBS-78 matrix created.
✔ [2024-10-12 08:53:22.469042]: DBS-1248 matrix created.
ℹ [2024-10-12 08:53:22.469775]: Return SBS-78 as major matrix.
ℹ [2024-10-12 08:53:22.471114]: INDEL matrix generation - start.
✔ [2024-10-12 08:53:23.063428]: Reference sequences queried from genome.
✔ [2024-10-12 08:53:23.064724]: INDEL length extracted.
✔ [2024-10-12 08:53:23.118635]: Adjacent copies counted.
✔ [2024-10-12 08:53:23.145021]: Microhomology size calculated.
✔ [2024-10-12 08:53:23.183159]: INDEL records classified into different components (types).
✔ [2024-10-12 08:53:23.185225]: ID-28 matrix created.
✔ [2024-10-12 08:53:23.187055]: ID-83 matrix created.
ℹ [2024-10-12 08:53:23.187692]: Return ID-83 as major matrix.
ℹ [2024-10-12 08:53:23.188366]: All types of matrices generation (APOBEC scores included) - end.
✔ [2024-10-12 08:53:23.188974]: Done.
ℹ [2024-10-12 08:53:23.189748]: 2.636 secs elapsed.
Outputing tally results for SBS
✖ [2024-10-12 08:53:23.194464]: You may choose wrong 'mode' option, this is designed for 'SBS'.
ℹ [2024-10-12 08:53:23.195215]: 5.636 secs elapsed.
An error is detected in extract process. Quit the program!
```

**Comment by ShixiangWang** [comment]
@szakallasn3 I can reproduce the error with R code

```r
library(sigminer)

maf = read_maf("~/Downloads/test_maf/5846_crc_bio.maf")
tally_list = sig_tally(maf, ref_genome = "BSgenome.Hsapiens.UCSC.hg38", mode = "ALL")
output_tally(tally_list$SBS_96[rowSums(tally_list$SBS_96) > 0, ] %>% t(), 
             result_dir = "~/Downloads/test_maf/test_out/", mut_type = "SBS")
```

As you only input one sample data, the `t()` will drop the dimession in R and cause the error. I will push a fix to make it work.

However, please note that `extract` is not suitable for data from one-sample. In such case, `fit` is recommended (`~/Documents/GitHub/sigflow/sigflow.R fit -i 5846_crc_bio.maf -o test_out -g hg38 --verbose`).

**Comment by ShixiangWang** [comment]
Now you can use the latest code from GitHub. However, it still fails as one sample is not supported for extract command.

**Comment by szakallasn3** [comment]
Dear @ShixiangWang, many thanks for your help! 
I cloned the latest release of sigprofiler, and now with the fit command it works fine for a single sample.
